### PR TITLE
Remove TLS from metrics endpoints

### PR DESCRIPTION
**Pull request by heycait**
[#172292206]

This removes TLS from the metrics endpoints of log-cache, gateway, syslog-server, and cf-auth-proxy.

This is pointing to a branch in log-cache-release https://github.com/cloudfoundry/log-cache-release/tree/metrics-tls-optional where the code is modified to make TLS for metrics endpoints optional and Dockerfiles are updated to remove the metrics certs as defaults.

### CODE REVIEW

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by heycait** [comment]
Updated the pipeline to not use the `bin/install-cf.sh`. Also temporarily changed it to point to a branch of cf-for-k8s because these changes require changes to `config/logging` as well.

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Pull request merged**
