### PR TITLE
Remove VirtualService config

### PR DESCRIPTION
**Pull request by mike1808**
- Networking configuration will be part of cf-for-k8s

~~Please **don't merge** this until [the PR in cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s/pull/525) is merged.~~

Co-authored-by: Kauana dos Santos <kdossantos@vmware.com>

### CODE REVIEW

**Comment by Benjamintf1** [comment]
@mike1808 any reason this isn't enabled/disabled by flag? might make things easier. We could merge a flagged version whenever, and then flip the flag and add the ingress in cf-for-k8s at the same time.

**Comment by mike1808** [comment]
@Benjamintf1 sorry for confusion. We're not going to add a flag because Ingress is going to have the same functionality as VirtualService. We'll work on this after our dev branch in cf-for-k8s is merged.

**Comment by mike1808** [comment]
We have this story https://www.pivotaltracker.com/story/show/175359509 for it.

**Comment by heycait** [comment]
Closing this issue as this has not made it into cf-for-k8s (https://github.com/cloudfoundry/cf-for-k8s/pull/532) and was work to migrate over to Contour that got put down.

**Pull request closed without merging**
