### PR TITLE
Remove VirtualService config

### PR DESCRIPTION
**Pull request by Benjamintf1**
this is the same pr, but within this repo so it can run tests.

### CODE REVIEW

**Comment by Benjamintf1** [comment]
same as #47

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Comment by Benjamintf1** [comment]
seems like nobody is looking at this pr :/ closing because notifications on my account.

**Comment by ghost** [comment]
Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! :eyes:

**Pull request closed without merging**
